
using System;
using Random = UnityEngine.Random;

public class WordsGenerator
{

    private string[] wordsList =
    {
        "code",
        "obscure",
        "passive",
        "harass",
        "amber",
        "angel",
        "greet",
        "sickness",
        "mutter",
        "organize",
        "pupil",
        "graduate",
        "door",
        "substitute",
        "wage",
        "slide",
        "hold",
        "bishop",
        "bear",
        "hospitality",
        "strange",
        "hemisphere",
        "conceive",
        "resource",
        "elbow",
        "collection",
        "stretch",
        "leadership",
        "absence",
        "value",
        "articulate",
        "flash",
        "apparatus",
        "ton",
        "executive",
        "cultural",
        "cruel",
        "describe",
        "background",
        "disco",
        "ant",
        "soar",
        "shake",
        "harmony",
        "dive",
        "speaker",
        "tropical",
        "distribute",
        "team",
        "disagree",
        "holiday",
        "costume",
        "album",
        "miner",
        "part",
        "soar",
        "restaurant",
        "preparation",
        "regard",
        "lease",
        "spin",
        "tread",
        "comfortable",
        "accumulation",
        "executrix",
        "recycle",
        "wolf",
        "catalogue",
        "trace",
        "cow",
        "deport",
        "minimize",
        "sample",
        "star",
        "influence",
        "proposal",
        "treat",
        "miserable",
        "stem",
        "presidential",
        "noise",
        "prescription",
        "precision",
        "perforate",
        "enhance",
        "survey",
        "eject",
        "opposed",
        "observation",
        "ego",
        "constitutional",
        "control",
        "whip",
        "herd",
        "price",
        "jest",
        "workshop",
        "quaint",
        "node",
        "folk"
    };

    public Word GetRandomWord()
    {
        Word word = new Word(wordsList[Random.Range(0, wordsList.Length - 1)]);
        return word;
    }
}
